# Generated by Django 6.0.5 on 2026-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
